@extends('layouts.base')
@section('title','لیست کاربران داشبورد')
@section('style')<link rel="stylesheet" href="{{ asset('assets/vendor/css/rtl/dataTables.dataTables.min.css') }}"/>@endsection
@section('content')
<div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="card-title mb-0">{{ $thispage['list'] }}</h5>@if(Gate::allows('can-access',['paneluser','insert']))<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addModal">{{ $thispage['add'] }}</button>@endif</div><div class="table-responsive"><table class="table table-striped table-bordered yajra-datatable"><thead><tr class="table-light"><th>نام</th><th>نقش</th><th>ایمیل</th><th>موبایل</th><th>وضعیت</th><th>عملیات</th></tr></thead></table></div></div></div>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content text-center"><div class="modal-header border-bottom-0"><h5 class="modal-title w-100">{{ $thispage['delete'] }}</h5><button type="button" class="btn-close position-absolute start-0 mx-3" data-bs-dismiss="modal"></button></div><div class="modal-body">آیا از حذف این کاربر مطمئن هستید؟</div><div class="modal-footer justify-content-center"><button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">انصراف</button><button type="button" class="btn btn-danger" id="confirmDelete">حذف</button></div></div></div></div>
@foreach(['add'=>'addModal','edit'=>'editModal'] as $mode=>$modalId)<div class="modal fade" id="{{ $modalId }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">{{ $mode==='add'?$thispage['add']:$thispage['edit'] }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="{{ $mode }}form" method="POST" @if($mode==='add') action="{{ route('paneluser.store') }}" @endif>@csrf @if($mode==='edit') @method('PATCH') @endif @include('panel.partials.panel-user-form',['prefix'=>$mode.'_','roles'=>$roles])<div class="text-end mt-3"><button type="submit" class="btn btn-primary">ذخیره اطلاعات</button></div></form></div></div></div></div>@endforeach
@endsection
@section('script')
<script src="{{ asset('assets/vendor/js/dataTables.min.js') }}"></script><script>
$(function(){const baseUrl=@json(url('panel/paneluser')),csrf=@json(csrf_token());let deleteId=null;const table=$('.yajra-datatable').DataTable({processing:true,serverSide:true,ajax:@json(route('paneluser.index')),columns:[{data:'name',name:'users.name'},{data:'title',name:'roles.title_fa'},{data:'email',name:'users.email'},{data:'phone',name:'users.phone'},{data:'status',name:'users.status'},{data:'action',name:'action',orderable:false,searchable:false}],language:{url:@json(asset('assets/vendor/js/fa.json'))}});const editModal=new bootstrap.Modal(document.getElementById('editModal')),deleteModal=new bootstrap.Modal(document.getElementById('deleteModal'));const error=x=>Swal.fire('خطا',x.responseJSON?.message||Object.values(x.responseJSON?.errors||{})?.flat()?.[0]||'عملیات انجام نشد.','error');function populate(d){['name','phone','email','national_id','role_id','birthday','gender','status'].forEach(k=>{const id=k==='role_id'?'edit_typeuser_id':'edit_'+k,e=document.getElementById(id);if(e)e.value=d[k]??'';});document.getElementById('edit_password').value='';document.getElementById('edit_password_confirmation').value='';}$(document).on('click','.edit-btn',function(){const id=Number($(this).data('id'));$.get(`${baseUrl}/${id}/edit`).done(r=>{populate(r.data);document.getElementById('editform').dataset.id=id;editModal.show();}).fail(error);});$(document).on('click','.delete-btn',function(){deleteId=Number($(this).data('id'));deleteModal.show();});$('#addform,#editform').on('submit',function(e){e.preventDefault();const f=this,isEdit=f.id==='editform',id=isEdit?Number(f.dataset.id):null,b=f.querySelector('button[type="submit"]'),old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال ذخیره...';$.ajax({url:isEdit?`${baseUrl}/${id}`:baseUrl,method:isEdit?'PATCH':'POST',data:$(f).serialize(),headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{isEdit?editModal.hide():bootstrap.Modal.getInstance(document.getElementById('addModal')).hide();if(!isEdit)f.reset();table.ajax.reload(null,false);Swal.fire('موفق',r.message||'کاربر ذخیره شد.','success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});$('#confirmDelete').on('click',function(){if(!deleteId)return;const b=this,old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال حذف...';$.ajax({url:`${baseUrl}/${deleteId}`,method:'DELETE',data:{_token:csrf},headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{deleteModal.hide();table.ajax.reload(null,false);Swal.fire('موفق',r.message||'کاربر حذف شد.','success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});});
</script>@endsection
