@extends('layouts.base')
@section('title','مدیریت نقش کاربران داشبورد')
@section('style')
<link rel="stylesheet" href="{{ asset('assets/vendor/css/rtl/dataTables.dataTables.min.css') }}"/>
@endsection
@section('content')
<div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="card-title mb-0">{{ $thispage['list'] }}</h5>@if(Gate::allows('can-access',['roleuser','insert']))<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addModal">{{ $thispage['add'] }}</button>@endif</div><div class="table-responsive"><table class="table table-striped table-bordered yajra-datatable"><thead><tr class="table-light"><th>عنوان فارسی</th><th>عنوان انگلیسی</th><th>دسترسی</th><th>وضعیت</th><th>عملیات</th></tr></thead></table></div></div></div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content text-center"><div class="modal-header border-bottom-0"><h5 class="modal-title w-100">{{ $thispage['delete'] }}</h5><button type="button" class="btn-close position-absolute start-0 mx-3" data-bs-dismiss="modal"></button></div><div class="modal-body">آیا از حذف این نقش مطمئن هستید؟</div><div class="modal-footer justify-content-center"><button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">انصراف</button><button type="button" class="btn btn-danger" id="confirmDelete">حذف</button></div></div></div></div>

<div class="modal fade" id="addModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">{{ $thispage['add'] }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="addform" action="{{ route('roleuser.store') }}" method="POST">@csrf @include('panel.partials.role-basic-form',['prefix'=>'add_'])<div class="text-end mt-3"><button type="submit" class="btn btn-primary">ذخیره اطلاعات</button></div></form></div></div></div></div>

<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">{{ $thispage['edit'] }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="editform" method="POST">@csrf @method('PATCH') @include('panel.partials.role-basic-form',['prefix'=>'edit_'])<div class="mt-3"><label class="form-label" for="edit_permission_id">دسترسی‌های نقش</label><select name="permission_id[]" id="edit_permission_id" class="form-control" multiple>@foreach($permissions as $permission)<option value="{{ $permission->id }}">{{ $permission->label ?: $permission->slug }}</option>@endforeach</select></div><div class="text-end mt-3"><button type="submit" class="btn btn-primary">ذخیره اطلاعات</button></div></form></div></div></div></div>

<div class="modal fade" id="permissionsModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="permissionsModalTitle">مدیریت دسترسی‌ها</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="permissionform">@csrf<input type="hidden" name="type" value="permission_update"><div class="table-responsive"><table class="table table-bordered align-middle"><thead><tr><th>صفحه</th><th>مشاهده</th><th>افزودن</th><th>ویرایش</th><th>حذف</th></tr></thead><tbody>@foreach($permissions as $permission)<tr data-permission-row="{{ $permission->id }}"><td>{{ $permission->label ?: $permission->slug }}</td>@foreach(['can_view'=>'مشاهده','can_insert'=>'افزودن','can_edit'=>'ویرایش','can_delete'=>'حذف'] as $action=>$label)<td class="text-center"><input class="form-check-input permission-action" type="checkbox" data-permission-id="{{ $permission->id }}" data-action="{{ $action }}" name="permissions[{{ $permission->id }}][{{ $action }}]" value="1"></td>@endforeach</tr>@endforeach</tbody></table></div><div class="text-end"><button type="submit" class="btn btn-primary">ذخیره دسترسی‌ها</button></div></form></div></div></div></div>
@endsection
@section('script')
<script src="{{ asset('assets/vendor/js/dataTables.min.js') }}"></script>
<script>
$(function(){
 const baseUrl=@json(url('panel/roleuser')),csrf=@json(csrf_token());let deleteId=null,currentRoleId=null;
 const table=$('.yajra-datatable').DataTable({processing:true,serverSide:true,ajax:@json(route('roleuser.index')),columns:[{data:'title_fa',name:'roles.title_fa'},{data:'title',name:'roles.title'},{data:'permission',name:'permission',orderable:false,searchable:false},{data:'status',name:'roles.status'},{data:'action',name:'action',orderable:false,searchable:false}],language:{url:@json(asset('assets/vendor/js/fa.json'))}});
 const editModal=new bootstrap.Modal(document.getElementById('editModal')),permissionModal=new bootstrap.Modal(document.getElementById('permissionsModal')),deleteModal=new bootstrap.Modal(document.getElementById('deleteModal'));
 const error=x=>Swal.fire('خطا',x.responseJSON?.message||Object.values(x.responseJSON?.errors||{})?.flat()?.[0]||'عملیات انجام نشد.','error');
 function loadRole(id,done){$.get(`${baseUrl}/${id}/edit`).done(r=>done(r.data)).fail(error);}
 $(document).on('click','.edit-btn',function(){const id=Number($(this).data('id'));loadRole(id,d=>{currentRoleId=id;document.getElementById('edit_title_fa').value=d.title_fa??'';document.getElementById('edit_title').value=d.title??'';document.getElementById('edit_status').value=d.status??4;const select=document.getElementById('edit_permission_id');Array.from(select.options).forEach(o=>o.selected=(d.permission_ids||[]).map(Number).includes(Number(o.value)));editModal.show();});});
 $(document).on('click','.permission-btn',function(){const id=Number($(this).data('id'));loadRole(id,d=>{currentRoleId=id;document.getElementById('permissionsModalTitle').textContent=`مدیریت دسترسی‌ها: ${d.title_fa||d.title||''}`;document.querySelectorAll('.permission-action').forEach(c=>c.checked=false);Object.entries(d.actions||{}).forEach(([pid,actions])=>Object.entries(actions).forEach(([action,value])=>{const c=document.querySelector(`.permission-action[data-permission-id="${pid}"][data-action="${action}"]`);if(c)c.checked=Boolean(value);}));document.querySelectorAll('[data-permission-row]').forEach(row=>{row.style.display=(d.permission_ids||[]).map(Number).includes(Number(row.dataset.permissionRow))?'':'none';});permissionModal.show();});});
 $(document).on('click','.delete-btn',function(){deleteId=Number($(this).data('id'));deleteModal.show();});
 $('#addform').on('submit',function(e){e.preventDefault();const f=this,b=f.querySelector('button[type="submit"]'),old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال ذخیره...';$.ajax({url:baseUrl,method:'POST',data:$(f).serialize(),headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{bootstrap.Modal.getInstance(document.getElementById('addModal')).hide();f.reset();table.ajax.reload(null,false);Swal.fire('موفق',r.message,'success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});
 $('#editform').on('submit',function(e){e.preventDefault();if(!currentRoleId)return;const f=this,b=f.querySelector('button[type="submit"]'),old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال ذخیره...';$.ajax({url:`${baseUrl}/${currentRoleId}`,method:'PATCH',data:$(f).serialize(),headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{editModal.hide();table.ajax.reload(null,false);Swal.fire('موفق',r.message,'success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});
 $('#permissionform').on('submit',function(e){e.preventDefault();if(!currentRoleId)return;const f=this,b=f.querySelector('button[type="submit"]'),old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال ذخیره...';$.ajax({url:`${baseUrl}/${currentRoleId}`,method:'PATCH',data:$(f).serialize(),headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{permissionModal.hide();table.ajax.reload(null,false);Swal.fire('موفق',r.message,'success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});
 $('#confirmDelete').on('click',function(){if(!deleteId)return;const b=this,old=b.innerHTML;b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> در حال حذف...';$.ajax({url:`${baseUrl}/${deleteId}`,method:'DELETE',data:{_token:csrf},headers:{'X-CSRF-TOKEN':csrf}}).done(r=>{deleteModal.hide();table.ajax.reload(null,false);Swal.fire('موفق',r.message,'success');}).fail(error).always(()=>{b.disabled=false;b.innerHTML=old;});});
});
</script>
@endsection
